
auths:
  vyos:
    security_level: authPriv
    username: obs
    password: ${SNMP_AUTH_PASSWORD}
    auth_protocol: SHA
    priv_protocol: AES
    priv_password: ${SNMP_PRIVACY_PASSWORD}
    version: 3
  juniper:
    security_level: authPriv
    username: obs
    password: ${SNMP_AUTH_PASSWORD}
    auth_protocol: SHA
    priv_protocol: AES
    priv_password: ${SNMP_PRIVACY_PASSWORD}
    version: 3

  # palo:
  #   community: public
  #   # version: "2c"

# list of modules:
# - vyos_system
# - vyos_ip
# - cisco_aci
# - juniper_apstra_interface
# - juniper_apstra_chassis
# - juniper_apstra_psu_power

modules:
  vyos_system:
    walk:
    - 1.3.6.1.2.1.1
    metrics:
    - name: sysContact
      oid: 1.3.6.1.2.1.1.4
      type: DisplayString
      help: The textual identification of the contact person for this managed node,
        together with information on how to contact this person - 1.3.6.1.2.1.1.4
  vyos_ip:
    walk:
    - 1.3.6.1.2.1.4.21
    metrics:
    - name: ipRouteDest
      oid: 1.3.6.1.2.1.4.21.1.1
      type: DisplayString
      help: ip routes
  cisco_aci:
    walk:
    - 1.3.6.1.4.1.9.9.109.1.1.1.1.7
    - 1.3.6.1.4.1.9.9.109.1.1.1.1.12.1
    - 1.3.6.1.4.1.9.9.109.1.1.1.1.13.1
    # - 1.3.6.1.4.1.9.9.117.1.4.1.1.1
    # - 1.3.6.1.4.1.9.9.117.1.1.2.1.2
    # - 1.3.6.1.4.1.9.9.796.1.1.1.1.2
    max_repetitions: 8
    timeout: 15s
    retries: 3
    metrics:
    - name: cpmCPUTotal1minRev
      oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.7
      type: gauge
      help: The overall CPU busy percentage in the last 1 minute period - 1.3.6.1.4.1.9.9.109.1.1.1.1.7
    - name: MemUsed
      oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.12.1
      type: gauge
      help: Memory Usage
    - name: MemFree
      oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.13.1
      type: gauge
      help: Memory Free
    - name: FAN_Status
      oid: 1.3.6.1.4.1.9.9.117.1.4.1.1.1
      type: gauge
      help: Fan Status
      indexes:
        - labelname: fan_id
          type: gauge
    - name: PSU_Status
      oid: 1.3.6.1.4.1.9.9.117.1.1.2.1.2
      type: gauge
      help: PSU Status
      indexes:
        - labelname: psu_id
          type: gauge
    - name: aciNodeStatus
      oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.7
      type: gauge
      help: Operational status of each fabric node.
  # panorama_cpu:
  #   walk:
  #     - 1.3.6.1.2.1.25.3  
  #   metrics:
  #     - name: hrProcessorLoad
  #       oid: 1.3.6.1.2.1.25.3.3.1.2
  #       type: gauge
  #       help: "Average CPU load"

  juniper_apstra_ifDescr:
    walk:
      - 1.3.6.1.2.1.2.2.1.2 # ifDescr
    max_repetitions: 8
    timeout: 30s
    retries: 3
    metrics:
      - name: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: DisplayString
        help: Textual name of interface
        indexes:
          - labelname: ifIndex
            type: gauge

  juniper_apstra_ifOperStatus:
    walk:
      - 1.3.6.1.2.1.2.2.1.8 # ifOperStatus
    max_repetitions: 8
    timeout: 30s
    retries: 3
    metrics:
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        help: The current operational state of the interface (1=up, 2=down, 3=testing, 4=unknown, 5=dormant, 6=notPresent, 7=lowerLayerDown)
        indexes:
          - labelname: ifIndex
            type: gauge


  juniper_apstra_ifInOctet:
    walk:
      - 1.3.6.1.2.1.2.2.1.10 # ifInOctet
    max_repetitions: 8
    timeout: 30s
    retries: 3
    metrics:
      - name: ifInOctets
        oid: 1.3.6.1.2.1.2.2.1.10
        type: counter
        help: The total number of octets received on the interface
        indexes:
          - labelname: ifIndex
            type: gauge

  juniper_apstra_ifOutOctets:
    walk:
      - 1.3.6.1.2.1.2.2.1.16 # ifOutOctets
    max_repetitions: 8
    timeout: 30s
    retries: 3
    metrics:
      - name: ifOutOctets
        oid: 1.3.6.1.2.1.2.2.1.16
        type: counter
        help: The total number of octets transmitted on the interface
        indexes:
          - labelname: ifIndex
            type: gauge

  juniper_apstra_chassis:
    walk:
      - 1.3.6.1.4.1.2636.3.1.2 # jnxBoxDescr
      - 1.3.6.1.4.1.2636.3.1.3 # jnxBoxSerialNo
      - 1.3.6.1.4.1.2636.3.1.4 # jnxBoxRevision
      - 1.3.6.1.4.1.2636.3.1.16 # jnxBoxKernelMemoryUsedPercent
      - 1.3.6.1.4.1.2636.3.1.17 # jnxBoxSystemDomainType
      - 1.3.6.1.4.1.2636.3.1.18 # jnxBoxPersonality
      - 1.3.6.1.4.1.2636.3.1.5 # jnxBoxInstalled
      - 1.3.6.1.4.1.2636.3.1.6 # jnxContainersTable
    max_repetitions: 8
    timeout: 30s
    retries: 3
    metrics:
      - name: jnxBoxDescr
        oid: 1.3.6.1.4.1.2636.3.1.2
        type: DisplayString
        help: Chassis or product description (jnxBoxDescr)

      - name: jnxBoxSerialNo
        oid: 1.3.6.1.4.1.2636.3.1.3
        type: DisplayString
        help: Chassis serial number (jnxBoxSerialNo)

      - name: jnxBoxRevision
        oid: 1.3.6.1.4.1.2636.3.1.4.0
        type: DisplayString
        help: Chassis hardware revision (jnxBoxRevision)

      - name: jnxBoxKernelMemoryUsedPercent
        oid: 1.3.6.1.4.1.2636.3.1.16
        type: gauge
        help: Kernel memory used percent (jnxBoxKernelMemoryUsedPercent)

      - name: jnxBoxSystemDomainType
        oid: 1.3.6.1.4.1.2636.3.1.17
        type: gauge
        help: System domain type (jnxBoxSystemDomainType)

      - name: jnxBoxPersonality
        oid: 1.3.6.1.4.1.2636.3.1.18.0
        type: DisplayString
        help: Chassis personality (jnxBoxPersonality)
        lookups:
          - labels: [personality]
            labelname: personality
            oid: 1.3.6.1.4.1.2636.3.1.18.0

      - name: jnxBoxInstalled
        oid: 1.3.6.1.4.1.2636.3.1.5
        type: gauge
        help: "Is the physical box installed (jnxBoxInstalled)?"

      - name: jnxContainersIndex
        oid: 1.3.6.1.4.1.2636.3.1.6.1.1.2
        type: gauge
        help: "Unique index of the hardware container"

  juniper_apstra_psu_power:
    walk:
      - 1.3.6.1.4.1.2636.3.58.1.2.1.1 # jnxPsuAvailableDeviceCount
      - 1.3.6.1.4.1.2636.3.58.1.2.1.5 # jnxPsuChassisPowerReserved
      - 1.3.6.1.4.1.2636.3.58.1.2.1.6 # jnxPsuChassisPowerAllocated
      - 1.3.6.1.4.1.2636.3.58.1.2.1.9 # jnxPsuChassisPowerConsumed
      - 1.3.6.1.4.1.2636.3.58.1.2.1.7 # jnxPsuRedundantPowerAvailable
      - 1.3.6.1.4.1.2636.3.58.1.2.1.8 # jnxPsuTotalPowerAvailable
    max_repetitions: 8
    timeout: 30s
    retries: 3
    metrics:
      - name: jnxPsuAvailableDeviceCount
        oid: 1.3.6.1.4.1.2636.3.58.1.2.1.1
        type: gauge
        help: Number of PSU units available online in the system (jnxPsuAvailableDeviceCount).

      - name: jnxPsuChassisPowerReserved
        oid: 1.3.6.1.4.1.2636.3.58.1.2.1.5
        type: gauge
        help: Power reserved for chassis in Watts (jnxPsuChassisPowerReserved).

      - name: jnxPsuChassisPowerAllocated
        oid: 1.3.6.1.4.1.2636.3.58.1.2.1.6
        type: gauge
        help: Power allocated for chassis in Watts (jnxPsuChassisPowerAllocated).

      - name: jnxPsuChassisPowerConsumed
        oid: 1.3.6.1.4.1.2636.3.58.1.2.1.9
        type: gauge
        help: Total power consumed by the entire system (jnxPsuChassisPowerConsumed).

      - name: jnxPsuRedundantPowerAvailable
        oid: 1.3.6.1.4.1.2636.3.58.1.2.1.7
        type: gauge
        help: Redundant power available for system (jnxPsuRedundantPowerAvailable).

      - name: jnxPsuTotalPowerAvailable
        oid: 1.3.6.1.4.1.2636.3.58.1.2.1.8
        type: gauge
        help: Power (in Watts) which could be made available for redundancy (jnxPsuTotalPowerAvailable).
